name: Code audit

on: [push, pull_request]

jobs:
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest # or any other PHP version you are using
          extensions: mbstring, ctype, iconv, xml, dom
          tools: composer, cs2pr

      - name: ğŸ’¾ Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: ğŸ” Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR12 --report=checkstyle ./src/ | cs2pr